# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: devise_lastseenable 0.0.6 ruby lib

Gem::Specification.new do |s|
  s.name = "devise_lastseenable".freeze
  s.version = "0.0.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["ctide".freeze]
  s.date = "2017-11-08"
  s.description = "This ensures that devise will update a last_seen flag on the model whenever you check if a user is authed.".freeze
  s.email = "christide@christide.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "devise_lastseenable.gemspec",
    "lib/devise_lastseenable.rb",
    "lib/devise_lastseenable/hooks/lastseenable.rb",
    "lib/devise_lastseenable/model.rb",
    "lib/devise_lastseenable/rails.rb",
    "lib/devise_lastseenable/version.rb",
    "lib/generators/devise_lastseenable/devise_lastseenable_generator.rb",
    "lib/generators/devise_lastseenable/templates/migration.rb",
    "test/helper.rb",
    "test/test_devise_lastseenable.rb"
  ]
  s.homepage = "http://github.com/craftydevil/devise_lastseenable".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.8".freeze
  s.summary = "This ensures that devise will update a last_seen flag on the model whenever you check if a user is authed.".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>.freeze, [">= 3.0.4"])
      s.add_runtime_dependency(%q<devise>.freeze, [">= 0"])
      s.add_development_dependency(%q<shoulda>.freeze, [">= 0"])
      s.add_development_dependency(%q<bundler>.freeze, [">= 0"])
      s.add_development_dependency(%q<jeweler>.freeze, [">= 0"])
    else
      s.add_dependency(%q<rails>.freeze, [">= 3.0.4"])
      s.add_dependency(%q<devise>.freeze, [">= 0"])
      s.add_dependency(%q<shoulda>.freeze, [">= 0"])
      s.add_dependency(%q<bundler>.freeze, [">= 0"])
      s.add_dependency(%q<jeweler>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>.freeze, [">= 3.0.4"])
    s.add_dependency(%q<devise>.freeze, [">= 0"])
    s.add_dependency(%q<shoulda>.freeze, [">= 0"])
    s.add_dependency(%q<bundler>.freeze, [">= 0"])
    s.add_dependency(%q<jeweler>.freeze, [">= 0"])
  end
end

